antras(yannis, maria).
pateras(yannis, kostas).
mitera(maria, kostas).
pateras(kostas, anna).
pateras(kostas, aris).
mitera(soula, anna).
mitera(soula, aris).
antras(kostas, soula).
adelfi(anna, aris).
adelfi(anna, kostas).